project:
  title: "streetscape"
  execute-dir: project
  render:
    - CPJ_prospectus.qmd
    - streetscape_slides.qmd

date-format: "MMM DD, YYYY HH:mm:ss z"
lang: en
df-print: kable
number-sections: true
linkcolor: blue
urlcolor: blue
pdfa: 2a

cite-method: citeproc
bibliography: ["/Users/connor/Zotero/My_Library.json", "grateful-refs.bib"]
biblio-title: References
reference-section-title: References
biblio-style: authoryear
biblatexoptions: "isbn=false, url=false"
link-citations: true

format:
  pdf: default
  docx: default
  html:
    anchor-sections: true
    toc: true
    toc-depth: 2
