project:
  title: "streetscape"
  execute-dir: project
  render:
    - CPJ_prospectus.qmd

date-format: "MMM DD, YYYY HH:mm:ss z"
lang: en
df-print: kable
number-sections: true
linkcolor: blue
urlcolor: blue

cite-method: citeproc
bibliography: "/Users/connor/Zotero/My_Library.json"
biblio-title: References
biblio-style: authoryear
biblatexoptions: "isbn=false, url=false"

format:
  pdf: default
  docx: default
  html:
    anchor-sections: true
    toc: true
    toc-depth: 2
