project:
  title: "streetscape"
  execute-dir: project

date-format: MMM DD, YYYY HH:mm:ss z
lang: en

df-print: kable
number-sections: true
linkcolor: blue
urlcolor: blue

cite-method: citeproc
bibliography: "/Users/connor/Zotero/My_Library.json"
biblio-title: References
biblio-style: authoryear
biblatexoptions: "isbn=false, url=false"

format:
  pdf:
    keep-tex: true
  docx: default
  html:
    anchor-sections: true

