---
title: ATP 2017 Overview
author: Connor P. Jackson
date: "`r format(Sys.time(), '%B %d, %Y - %H:%M %Z')`"
lang: en
output:
  bookdown::html_document2:
    fig_caption: yes
    number_sections: yes
    highlight: textmate
    toc: yes
    toc_depth: 2
    toc_float: yes
    df_print: !expr pander::pander
  bookdown::pdf_document2:
    fig_caption: yes
    toc: yes
    number_sections: yes
    keep_tex: yes
    pandoc_args: "--wrap=none"
    citation_package: biblatex
    md_extensions: -auto_identifiers
    df_print: !expr pander::pander
linestretch: 1.1
linkcolor: blue
urlcolor: blue
link-citations: true
bibliography: ["/Users/connor/cpjackson@berkeley.edu - Google Drive/My Drive/CitationManagement/library.bib", grateful-refs.bib]
reference-section-title: References
biblio-title: References
biblio-style: authoryear
biblatexoptions: "isbn=false, url=false"
pdfa: 2a
---

```{r setup, include=FALSE}
library(knitr)
library(pander)
library(rmarkdown)
library(grateful)
library(data.table)
# read_chunk("FILENAMEHERE")
options(knitr.kable.NA = '')
panderOptions("digits", 3)
panderOptions("table.split.cells", 15)
panderOptions("table.split.table", 120)
```

```{r citations, echo=FALSE}
citerefs <- cite_packages(output = "citekeys", include.RStudio = TRUE)
nocite_references(citerefs, citation_processor = 'pandoc')
```

```{r import-data}
headers <- fread("/Users/connor/cpjackson@berkeley.edu - Google Drive/My Drive/Streetscape/ATP 2017/headers.csv")
headers <- headers[include == TRUE, header]
proj <- fread("/Users/connor/cpjackson@berkeley.edu - Google Drive/My Drive/Streetscape/ATP 2017/ATP2017_data.csv", 
              select = headers, check.names = TRUE)

setnames(proj, gsub("form.0..", "", colnames(proj), fixed = TRUE))
proj[, atp_year := 2017]
```

```{r}
proj[, .N, keyby = .(A3_P)]
```


