---
title: "Streetscape: SafeGraph exploration"
author: Connor P. Jackson
date: "`r format(Sys.time(), '%B %d, %Y - %H:%M %Z')`"
lang: en
output:
  html_notebook:
    fig_caption: yes
    number_sections: yes
    df_print: !expr pander::pander
  bookdown::html_document2:
    fig_caption: yes
    number_sections: yes
    highlight: textmate
    toc: yes
    toc_depth: 2
    toc_float: yes
    df_print: !expr pander::pander
  bookdown::pdf_document2:
    fig_caption: yes
    toc: yes
    number_sections: yes
    keep_tex: yes
    pandoc_args: "--wrap=none"
    citation_package: biblatex
    md_extensions: -auto_identifiers
    df_print: !expr pander::pander
linkcolor: blue
urlcolor: blue
link-citations: true
reference-section-title: References
biblio-title: References
biblio-style: authoryear
biblatexoptions: "isbn=false, url=false"
pdfa: 2a
---

```{r setup, include=FALSE}
library(knitr)
library(pander)
library(rmarkdown)
library(grateful)
library(SafeGraphR)
library(data.table)
options(knitr.kable.NA = '')
panderOptions("digits", 3)
panderOptions("table.split.cells", 15)
panderOptions("table.split.table", 120)
```

```{r}

cols_to_use <- c("date_range_start", "date_range_end", "placekey", "sg_c__parent_placekey", 
                 "sg_c__location_name", "sg_c__top_category", "sg_c__sub_category", 
                 "sg_c__naics_code", "sg_c__latitude", "sg_c__longitude", "sg_c__street_address",
                 "sg_c__city", "sg_c__region", "sg_c__postal_code", "sg_c__opened_on", 
                 "sg_c__closed_on", "sg_wp__raw_visit_counts", "sg_wp__raw_visitor_counts", 
                 "sg_wp__poi_cbg", "sg_wp__visitor_home_cbgs", "sg_wp__visitor_home_aggregation",
                 "sg_wp__visitor_daytime_cbgs", "sg_wp__distance_from_home", "sg_wp__median_dwell",
                 "sg_wp__bucketed_dwell_times", "sg_wp__normalized_visits_by_state_scaling", 
                 "sg_wp__normalized_visits_by_total_visits", "sg_wp__normalized_visits_by_total_visitors")

sg <- fread("/Volumes/GoogleDrive-114494246111519559339/My Drive/Streetscape/Safegraph CA Data thru 2022-02-07/CA-part1.csv.gz",
            na.strings = c("", "{}"), select = cols_to_use)
# panel <- fread("/Volumes/GoogleDrive-114494246111519559339/My Drive/Streetscape/Safegraph CA Data thru 2022-02-07/safegraph_home_panel_summary-part1.csv.gz")
# norm <- fread("/Volumes/GoogleDrive-114494246111519559339/My Drive/Streetscape/Safegraph CA Data thru 2022-02-07/safegraph_normalization_stats.csv.gz")
# visit <- fread("/Volumes/GoogleDrive-114494246111519559339/My Drive/Streetscape/Safegraph CA Data thru 2022-02-07/safegraph_visit_panel_summary.csv.gz")

# use normalized_visits_by_state_scaling -> "If we expect that someone in the SafeGraph sample is equally likely to visit a given POI as another random person in the population, then normalized_visits_by_state_scaling represents how many people (not just how many SafeGraph users) visited a given location"

```

