---
title: Streetscape Changes and Infrastructure Equity
author: Connor P. Jackson
date: April 6, 2022
lang: en
output:
  ioslides_presentation:
    transition: faster
    df_print: !expr pander::pander
    css: slides.css
linestretch: 1.1
linkcolor: blue
urlcolor: blue
link-citations: true
bibliography: "/Users/connor/cpjackson@berkeley.edu - Google Drive/My Drive/CitationManagement/library.bib"
---

# Motivation and Question

## Motivation

History: Interstate Highways, Urban Renewal

Today: Bike lanes as Harbinger of Displacement, Gentrification

Need to understand the benefits, the costs, and who bears each

## Research Question

1. What are the impacts of adding a bike lane, removing a traffic lane, or removing on-street parking on traffic throughput and speeds, visitation to adjacent businesses, crashes, and fatalities?
2. What are the magnitude and extent of spillovers from these projects on adjacent areas?
3. [Is there heterogeneity in who is impacted?]{.lighter}

# Example Project: Oakland, 14th Street

## Project Overview

>The project includes a reduction in travel lanes from four (4) to two (2); addition of Class IV protected bicycle lanes separated from travel by curbs and parked cars for maximum protection; improved pedestrian facilities including refuges, marked crossings, retimed signals, storm drain rain gardens, and transit boarding islands. 

## Map of Project Area

[Map, project diagram]

## Project Timeline

- Project Approval & Environmental Documentation: January 2016–December 2017
- Plans, Specifications, and Estimates: August 2019–November 2020
- Right of Way acquisition: August 2019–November 2020
- Construction: January 2021–July 2022

# Description of Data

## Project Data

[Project attributes page]

- Location
- Attributes
- Timeline
- Baseline use data
- _Scores_ (running variable)

## Outcome Data

- Visitor counts to points of interest (Safegraph)
- Traffic volumes and speeds (Streetlight)
- Crashes and Fatalities (SWITRS)


